<a href="https://colab.research.google.com/github/hiten4/Day21AM/blob/main/Day21_AM_Part_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create arrays (1D, 2D, 3D)

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

print(arr1[2])
print(arr2[0])
print(arr2[:, 1])
print(arr2[0:2, 1:3])

3
[1 2 3]
[2 5]
[[2 3]
 [5 6]]


# 2. Element-wise operations

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add = a + b
sub = a - b
mul = a * b

mean = np.mean(a)
var = np.var(a)
std = np.std(a)

print(add, sub, mul)
print(mean, var, std)

[5 7 9] [-3 -3 -3] [ 4 10 18]
2.0 0.6666666666666666 0.816496580927726



# 3. Broadcasting

In [3]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

vec = np.array([10, 20, 30])


broadcast_add = mat + vec


scalar_mul = mat * 2


vec_mul = mat * vec

print(broadcast_add)
print(scalar_mul)
print(vec_mul)


[[11 22 33]
 [14 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 10  40  90]
 [ 40 100 180]]



# 4. Vectorised operations

In [4]:
x = np.array([-2, -1, 0, 1, 2])

square = x ** 2
cube = x ** 3


x_pos = np.where(x < 0, 0, x)


min_val = x.min()
max_val = x.max()
normalized = (x - min_val) / (max_val - min_val)

print(square, cube, x_pos, normalized)

[4 1 0 1 4] [-8 -1  0  1  8] [0 0 0 1 2] [0.   0.25 0.5  0.75 1.  ]


# 5. Dataset operations

In [5]:

data = np.array([10, 45, 32, 67, 89, 23, 90, 12, 56])


top5 = np.sort(data)[-5:][::-1]


mat2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

row_sum = mat2.sum(axis=1)
col_sum = mat2.sum(axis=0)


threshold = 50
indices = np.where(data > threshold)

print(top5)
print(row_sum, col_sum)
print(indices)

[90 89 67 56 45]
[ 6 15] [5 7 9]
(array([3, 4, 6, 8]),)
